### ISSUE TITLE
One rule break atom-material-ui

### ISSUE THREAD

**Issue by mrleblanc101** [dthpham/tree-view-scope-lines#2]
Hi,
The background: transparent on the project root break atom-material-ui theme and does not seem to add or fix anything. I added an override in my atom stylesheet but I would be very happy if the problem could be fixed at the package level.
Here's a side-by-side of the problem:
![capture d ecran 2018-01-21 a 21 08 26](https://user-images.githubusercontent.com/17392251/35202272-b09846c0-feef-11e7-9afe-05ee671fa190.png)
![capture d ecran 2018-01-21 a 21 08 37](https://user-images.githubusercontent.com/17392251/35202273-b0a59398-feef-11e7-9b88-addc678912e9.png)

```css
.tree-view.tree-view-scope-lines .selected.project-root:before {
    /* background: transparent; */
    box-shadow: none;
    border-right: none;
    margin-left: initial;
}
```
